version: "3.8"

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    restart: unless-stopped
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      # Giới hạn kích thước message
      - KAFKA_CFG_MESSAGE_MAX_BYTES=1200000000
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=1200000000

      # Tạo sẵn 2 topic: incoming-emails và sending-emails
      - KAFKA_CREATE_TOPICS=incoming-emails:1:1,sending-emails:1:1
